# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_auto_20180106_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptoruser',
            name='cart_num',
        ),
    ]
