# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0003_remove_adaptoruser_cart_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'invalidusername',
            },
        ),
    ]
