# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_invalidusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidusername',
            name='invalid_type',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
