# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apps',
            options={'permissions': (('manage_apps', 'manage apps:create, delete'),)},
        ),
    ]
