# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-07 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0002_auto_20180107_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.Apps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authtoken',
            name='token',
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='authtoken',
            unique_together=set([('user', 'app')]),
        ),
    ]
