BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBXXXXXXBBBBBBBB
BBBBB BBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

BBBBBBBB
BBBBB BBBBBBBBBB
XXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBXXXXBBBBBBBB
BBBBB BBBBBBBBB XXXX XXXXXX XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXXXX  XXXXXXXXX  XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXX
        
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX 
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXX
        XXXXXX
XXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBBBBBB